name: Daily menu update

on:
  schedule:
    # Runs at 10:30pm and 12:30pm every day (UTC)
    - cron: '30 22,12 * * *'

jobs:

  scrape:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: gem install nokogiri open-uri firebase
        
    - name: Run scraper
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }}  
      run: ruby getmenu.rb
