name: Daily menu update

on:
  schedule:
    # Runs twice daily (12:00 UTC and 00:00 UTC)
    - cron: '0 12,0 * * *'
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-22.04
    
    timeout-minutes: 30

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.1

    - name: Cache Ruby gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-ruby-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-ruby-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2 libxslt1-dev --fix-missing

    - name: Install dependencies
      run: MAKEFLAGS="-j$(nproc)" gem install nokogiri open-uri firebase google-cloud-firestore

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Archive data
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }} 
        BASE_URL: ${{ secrets.BASE_URI }}
      run: ruby movedata.rb

    - name: Get UFPR menus
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }} 
        BASE_URL: ${{ secrets.BASE_URI }}
      run: ruby UFPR.rb

    - name: Get UFABC menus
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }} 
        BASE_URL: ${{ secrets.BASE_URI }}
      run: ruby UFABC.rb
      continue-on-error: true

    # - name: Get UFRGS menus
    #   env:
    #     FIREBASE_KEY: ${{ secrets.SECRET }} 
    #     BASE_URL: ${{ secrets.BASE_URI }}
    #   run: ruby UFRGS.rb
    #   continue-on-error: true

    - name: Add today's menu to archive and firestore
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }} 
        BASE_URL: ${{ secrets.BASE_URI }}
        GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      run: ruby movedata_today.rb

