name: Daily menu update

on:
  schedule:
    # Runs at 10:30pm and 12:30pm every day (UTC)
    - cron: '30 22,12 * * *'
  workflow_dispatch:

jobs:

  update-database:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: gem install nokogiri open-uri firebase google-cloud-firestore
      run:  gem install faraday-net_http 3.0.2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
        
    - name: Archive data
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }}  
        BASE_URL: ${{ secrets.BASE_URI }}
      run: ruby movedata.rb

    - name: Get menus
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }}  
        BASE_URL: ${{ secrets.BASE_URI }}
      run: ruby getmenu.rb

    - name: Add today's menu to archive and firestore
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }}  
        BASE_URL: ${{ secrets.BASE_URI }}
        GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      run: ruby movedata_today.rb
