name: Daily Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC

jobs:

  scrape:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: gem install nokogiri open-uri firebase
        
    - name: Run scraper
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }}  
      run: ruby scraper.rb