name: Analyse data

on:
  schedule:
    # Runs every 2 sundays at noon (UTC-3:00)
    - cron: '0 15 1-7,15-21 * 0'
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run script
              env:
                SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
              run: |
                python data_analysis.py