name: Weekly menu update

on:
  schedule:
    # Runs twice a week, on Monday and Thursday at 3 AM UTC
    - cron: '0 3 * * 1,4'
  workflow_dispatch:

jobs:

  update-database:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: gem install nokogiri open-uri firebase google-cloud-firestore

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
        
    - name: Archive data
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }}  
        BASE_URL: ${{ secrets.BASE_URI }}
      run: ruby movedata.rb

    - name: Get UFPR menus
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }}  
        BASE_URL: ${{ secrets.BASE_URI }}
      run: ruby UFPR.rb
    
    - name: Get UFABC menus
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }}  
        BASE_URL: ${{ secrets.BASE_URI }}
      run: ruby UFABC.rb

    - name: Add today's menu to archive and firestore
      env:
        FIREBASE_KEY: ${{ secrets.SECRET }}  
        BASE_URL: ${{ secrets.BASE_URI }}
        GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      run: ruby movedata_today.rb
